const DEFAULT_API_BASE = "http://127.0.0.1:8188"

const API_BASE =
  process.env.NEXT_PUBLIC_COMFY_API_BASE?.trim() || DEFAULT_API_BASE

const MAX_RESULTS_WHEN_EMPTY = 60
const HANDLE_OFFSET = 14

export { API_BASE, HANDLE_OFFSET, MAX_RESULTS_WHEN_EMPTY }
